
project_id = "uylujlvfyhftgaztwowf"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54326

[functions.send-telegram-notification]
verify_jwt = false

[functions.telegram-bot-webhook]
verify_jwt = false

[functions.send-assignment-email]
verify_jwt = false

[functions.send-appointment-email]
verify_jwt = false

[functions.send-appointment-confirmation]
verify_jwt = false

[functions.send-appointment-reminder]
verify_jwt = false

[functions.test-telegram-reminder]
verify_jwt = false

[edge-runtime]
enabled = true
port = 54327

[analytics]
enabled = false
